/**
 * Pull the three families Openbook uses out of Google Fonts and into the repo.
 *
 * Self-hosting is not a micro-optimisation here: the stylesheet is a
 * render-blocking third-party request on the critical path, and every visitor's
 * IP address reaches Google before a single number appears. Locally served, the
 * page needs no third-party origin at all, which is also what lets the
 * Content-Security-Policy go back to 'self'.
 *
 * Re-run with: node scripts/fetch-fonts.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises';

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

// Only the subsets the page can actually render: English text, plus the
// accented characters that turn up in place names.
const KEEP = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  'Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700',
  'Manrope:wght@400;500;600;700;800',
  'IBM+Plex+Mono:wght@400;500;600'
];

await mkdir('assets/fonts', { recursive: true });
const written = new Map();

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Each @font-face is preceded by a /* subset */ comment.
  const parts = css.split('/*').slice(1);
  for (const part of parts) {
    const subset = part.slice(0, part.indexOf('*/')).trim();
    if (!KEEP.has(subset)) continue;
    const face = part.slice(part.indexOf('*/') + 2);
    const src = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
    if (!src) continue;

    const name = src[1].split('/').pop();

    // Fraunces and Manrope are variable fonts: Google answers every requested
    // weight with the same file, so one rule per file is enough. Writing one
    // per weight would make the browser parse five rules to reach one download.
    const weights = face.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const seen = written.get(name);
    if (seen) {
      seen.weights.add(weights);
      continue;
    }

    const bytes = new Uint8Array(await (await fetch(src[1])).arrayBuffer());
    await writeFile(`assets/fonts/${name}`, bytes);
    written.set(name, {
      weights: new Set([weights]),
      face: face.trim().replace(src[1], `../fonts/${name}`),
      kb: Math.round(bytes.length / 1024),
      subset
    });
    console.log(`${subset.padEnd(10)} ${String(Math.round(bytes.length / 1024)).padStart(3)} KB  ${name}`);
  }
}

// A file serving several weights gets one rule spanning them, which is what
// `font-weight: 400 800` means to a variable font.
const blocks = [...written.values()].map((entry) => {
  const numbers = [...entry.weights].flatMap((w) => w.split(/\s+/)).map(Number).filter(Number.isFinite);
  if (numbers.length < 2) return entry.face;
  const range = `${Math.min(...numbers)} ${Math.max(...numbers)}`;
  return entry.face.replace(/font-weight:\s*[^;]+;/, `font-weight: ${range};`);
});

const header = `/*
 * Openbook's typefaces, served from this origin.
 *
 * Generated by scripts/fetch-fonts.mjs — edit that, not this. Fraunces and
 * Manrope are under the SIL Open Font License, IBM Plex Mono under the SIL OFL
 * as well; see assets/fonts/LICENSE.txt.
 */

`;
await writeFile('assets/css/fonts.css', header + blocks.join('\n\n') + '\n');
console.log(`\nassets/css/fonts.css: ${blocks.length} @font-face rules`);
